package StaticQueue;

import java.util.LinkedList;
import java.util.Queue;

public class Main {

	public static void main(String[] args) {
		StaticQueue q = new StaticQueue(); 
		System.out.println(q.size());
		System.out.println(q.isEmpty());
		//System.out.println(q.front());
		//q.dequeue();
		q.enqueue(5);
        q.enqueue(1);
        q.enqueue(9);
        q.enqueue(8);
        q.enqueue(6);
        q.enqueue(4);
        System.out.println(q);
        System.out.println("Posição "+q.indexOf(5));
        System.out.println("Tamanho da fila " + q.size());
        System.out.println(q.front());
        q.dequeue();
        System.out.println("Posição "+q.indexOf(5));
        System.out.println("Tamanho da fila " + q.size());
        System.out.println(q.front());
        q.dequeue();
        System.out.println(q);
        System.out.println("Posição "+q.indexOf(6));
        System.out.println("Primeiro da fila " + q.front());
        System.out.println("Tamanho da fila " + q.size());
        q.enqueue(5);
        System.out.println(q);
        System.out.println("Posição "+q.indexOf(5));
        q.enqueue(8);
        q.enqueue(78);
        q.enqueue(78);
        q.enqueue(78);
        q.enqueue(78);
        q.enqueue(5);
        System.out.println(q);
        System.out.println(q.size());
		System.out.println(q.isEmpty());
		System.out.println(q.front());
		System.out.println("Posição "+q.indexOf(78));
		System.out.println("Tamanho da fila " + q.size());
		System.out.println("------------------------------------");
		q.clear();
		System.out.println(q.isEmpty());
        System.out.println(q);
        System.out.println("Tamanho da fila " + q.size());
        //System.out.println(q.front());
        //q.dequeue();
        System.out.println("Posição "+q.indexOf(5));
        q.enqueue(5);
		q.enqueue(1);
		q.enqueue(9);
	    q.enqueue(8);
	    q.enqueue(6);
	    q.enqueue(4);
	    q.enqueue(5);
        q.enqueue(8);
        q.enqueue(78);
        q.enqueue(88);
        System.out.println(q);
        System.out.println("Posição "+q.indexOf(88));
        System.out.println("Tamanho da fila!!!! " + q.size());
        q.dequeue();
        q.enqueue(98);
        System.out.println(q);
        System.out.println("Posição "+q.indexOf(88));
        System.out.println("Posição "+q.indexOf(98));
        System.out.println("Tamanho da fila tava doido " + q.size());
        System.out.println(q.isEmpty());
        System.out.println(q);
        q.enqueue(68);
        System.out.println(q);
        System.out.println("Tamanho da fila " + q.size());
        q.enqueue(5);
		q.enqueue(1);
		q.enqueue(9);
	    q.enqueue(8);
	    q.enqueue(6);
	    q.enqueue(4);
	    q.enqueue(5);
        q.enqueue(8);
        q.enqueue(78);
        q.enqueue(88);
        System.out.println(q);
        System.out.println("Tamanho da fila mais uns: " + q.size());
        System.out.println(q.isEmpty());
		System.out.println(q.front());
        q.clear();
        System.out.println(q);
        System.out.println("------------------------------------");
        q.enqueue(5);
        q.enqueue(1);
        q.enqueue(9);
        q.enqueue(8);
        q.enqueue(6);
        q.enqueue(4);
        System.out.println("Posição "+q.indexOf(9));
        System.out.println(q);
        System.out.println("Tamanho da fila " + q.size());
        q.dequeue();
        System.out.println("Posição "+q.indexOf(6));
        System.out.println(q);
        q.enqueue(5);
        q.enqueue(8);
        q.enqueue(78);
        q.enqueue(78);
        q.enqueue(78);
        q.enqueue(78);
        q.enqueue(5);
        System.out.println(q);
        System.out.println("Posição "+q.indexOf(78));
        System.out.println(q.size());
		System.out.println(q.isEmpty());
	}

}
